apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: __AWS_ACCOUNT_ID__.dkr.ecr.us-east-1.amazonaws.com/voting_worker:__IMAGE_TAG__
        name: worker
